Update Build And Release.yml

diff --git a/.github/workflows/Build And Release.yml b/.github/workflows/Build And Release.yml
--- a/.github/workflows/Build And Release.yml
+++ b/.github/workflows/Build And Release.yml
@@ -1,8 +1,12 @@
-name: Build and Release Aseprite
+name: Build and release Aseprite
 
 on:
+  push:
+    branches:
+      - main
+    paths:
+      - 'BuildLog.md'
   workflow_dispatch:
-
 env:
   BUILD_TYPE: Release
 
@@ -14,44 +18,49 @@ jobs:
       download-link: ${{ steps.aseprite-link.outputs.download-link }}
       release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
     steps:
-      - name: Fetch Aseprite release link
+      - name: Fetch Aseprite Release Link
         id: aseprite-link
         run: |
-          echo "Fetching Aseprite release..."
+          echo "Fetching Aseprite latest release..."
           RELEASE_API="https://api.github.com/repos/aseprite/aseprite/releases/latest"
-          MATCH_REGEX="Aseprite-.*?-Source.zip"
-          DOWNLOAD_LINK=""
-          RELEASE_TAG=""
+          RESPONSE=$(curl -s $RELEASE_API)
+          RELEASE_TAG=$(echo "$RESPONSE" | jq -r '.tag_name')
+          DOWNLOAD_LINK=$(echo "$RESPONSE" | jq -r '.assets[] | select(.name | test("Aseprite-.*?-Source.zip")) | .browser_download_url')
 
-          for i in {1..10}; do
-            RESPONSE=$(curl -s $RELEASE_API)
-            RELEASE_TAG=$(echo "$RESPONSE" | jq -r '.tag_name')
-            echo "Release Tag: $RELEASE_TAG"
+          if [[ -z "$RELEASE_TAG" || -z "$DOWNLOAD_LINK" ]]; then
+            echo "Error: Failed to fetch release details!"
+            exit 1
+          fi
 
-            for asset in $(echo "$RESPONSE" | jq -r '.assets[].browser_download_url'); do
-              if [[ $asset =~ $MATCH_REGEX ]]; then
-                DOWNLOAD_LINK=$asset
-                break
-              fi
-            done
+          echo "Release Tag: $RELEASE_TAG"
+          echo "Download Link: $DOWNLOAD_LINK"
 
-            if [[ -n "$DOWNLOAD_LINK" ]]; then
-              echo "Found Aseprite release: $DOWNLOAD_LINK"
-              echo "download-link=$DOWNLOAD_LINK" >> $GITHUB_ENV
-              echo "release-tag=$RELEASE_TAG" >> $GITHUB_ENV
-              exit 0
-            fi
+          echo "release-tag=$RELEASE_TAG" >> $GITHUB_ENV
+          echo "download-link=$DOWNLOAD_LINK" >> $GITHUB_ENV
 
-            echo "Retrying after 10s..."
-            sleep 10
-          done
-
-          echo "Failed to fetch release!"
-          exit 1
+  create-release:
+    name: Create Release
+    runs-on: ubuntu-latest
+    needs: fetch-aseprite-info
+    permissions:
+      contents: write
+    outputs:
+      download-link: ${{ needs.fetch-aseprite-info.outputs.download-link }}
+      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
+    steps:
+      - uses: actions/checkout@v2
+      - uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
+          body: Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}
+          skipIfReleaseExists: true
+          token: ${{ secrets.GITHUB_TOKEN }}
 
   build-aseprite:
     name: Build Aseprite
-    needs: fetch-aseprite-info
+    needs: create-release
+    permissions:
+      contents: write
     runs-on: ${{ matrix.os }}
     strategy:
         matrix:
@@ -60,6 +69,7 @@ jobs:
     steps:
       - name: Install Dependencies (Linux)
         if: runner.os == 'Linux'
+        shell: bash
         run: |
           sudo apt-get update -qq
           sudo apt-get install -y \
@@ -70,7 +80,7 @@ jobs:
 
       - name: Clone Aseprite
         run: |
-          git clone --recursive -j8 https://github.com/aseprite/aseprite.git --branch ${{ env.release-tag }}
+          git clone --recursive -j8 https://github.com/aseprite/aseprite.git --branch ${{ needs.create-release.outputs.release-tag }}
 
       - name: Install Skia
         working-directory: aseprite
@@ -125,14 +135,21 @@ jobs:
 
       - name: Clean Up Build Folder
         working-directory: aseprite/build/bin
+        shell: bash
         run: find . -mindepth 1 ! \( -name 'aseprite' -o -name 'aseprite.exe' -o -name 'data' -prune \) -exec rm -rf {} +
 
       - name: Make Portable Zip
         working-directory: aseprite/build/bin
         run: echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini
 
-      - name: Archive Artifacts
-        uses: actions/upload-artifact@v4
+      - name: Create release
+        working-directory: aseprite/build/bin
+        run: 7z -tzip a Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip *
+
+      - name: Upload release
+        uses: svenstaro/upload-release-action@v2
         with:
-          name: aseprite-${{ matrix.os }}
-          path: aseprite/build/bin/*
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip
+          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip
+          tag: ${{ needs.create-release.outputs.release-tag }}
