Update Build And Release.yml

diff --git a/.github/workflows/Build And Release.yml b/.github/workflows/Build And Release.yml
--- a/.github/workflows/Build And Release.yml
+++ b/.github/workflows/Build And Release.yml
@@ -7,8 +7,51 @@ env:
   BUILD_TYPE: Release
 
 jobs:
+  fetch-aseprite-info:
+    name: Fetch Aseprite Release Info
+    runs-on: ubuntu-latest
+    outputs:
+      download-link: ${{ steps.aseprite-link.outputs.download-link }}
+      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
+    steps:
+      - name: Fetch Aseprite release link
+        id: aseprite-link
+        run: |
+          echo "Fetching Aseprite release..."
+          RELEASE_API="https://api.github.com/repos/aseprite/aseprite/releases/latest"
+          MATCH_REGEX="Aseprite-.*?-Source.zip"
+          DOWNLOAD_LINK=""
+          RELEASE_TAG=""
+
+          for i in {1..10}; do
+            RESPONSE=$(curl -s $RELEASE_API)
+            RELEASE_TAG=$(echo "$RESPONSE" | jq -r '.tag_name')
+            echo "Release Tag: $RELEASE_TAG"
+
+            for asset in $(echo "$RESPONSE" | jq -r '.assets[].browser_download_url'); do
+              if [[ $asset =~ $MATCH_REGEX ]]; then
+                DOWNLOAD_LINK=$asset
+                break
+              fi
+            done
+
+            if [[ -n "$DOWNLOAD_LINK" ]]; then
+              echo "Found Aseprite release: $DOWNLOAD_LINK"
+              echo "download-link=$DOWNLOAD_LINK" >> $GITHUB_ENV
+              echo "release-tag=$RELEASE_TAG" >> $GITHUB_ENV
+              exit 0
+            fi
+
+            echo "Retrying after 10s..."
+            sleep 10
+          done
+
+          echo "Failed to fetch release!"
+          exit 1
+
   build-aseprite:
     name: Build Aseprite
+    needs: fetch-aseprite-info
     runs-on: ${{ matrix.os }}
     strategy:
         matrix:
@@ -27,7 +70,7 @@ jobs:
 
       - name: Clone Aseprite
         run: |
-          git clone --recursive -j8 https://github.com/aseprite/aseprite.git --branch v1.3.13
+          git clone --recursive -j8 https://github.com/aseprite/aseprite.git --branch ${{ env.release-tag }}
 
       - name: Install Skia
         working-directory: aseprite
